#! /bin/sh

sxhkd &

###################################################
#                   PYWAL COLORS                  #
###################################################

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"


###################################################
#                     SETTINGS                    #
###################################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1  #1 selected

bspc config border_width         2
bspc config window_gap           6
bspc config top_padding        	 18  #like polybar height
bspc config left_padding       	 0
bspc config bottom_padding    	 0
bspc config split_ratio        	 0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


###################################################
#                      RULES                      #
###################################################

bspc rule -a Gimp           desktop='^8' state=floating follow=on
bspc rule -a Chromium       desktop='^1'
bspc rule -a Seq64          state=floating
bspc rule -a Screenkey      manage=off
bspc rule -a mpv            state=floating
bspc rule -a feh            state=floating


###################################################
#                   AUTOSTART                     #
###################################################

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
~/.config/polybar/launch.sh
wal -n -i ~/.config/bspwm/bg/stallman.jpg &                       # Wal detect colors
feh --bg-scale ~/.config/bspwm/bg/stallman.jpg &                  # Background
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &      # Policykit
#xfce4-power-manager &                                                 # XFCE4 PowerManager
compton -b --config ~/.config/compton/compton.conf &              # Compton
dunst &                                                               # Notify system
wicd-gtk -t &                                                         # Network manager
parcellite &                                                          # Clipboard manager
emacs --daemon &                                                      # Emacs daemon
